"""users table

Revision ID: 22091a5ca65a
Revises: 7321151c25a9
Create Date: 2020-04-01 17:22:23.193932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22091a5ca65a'
down_revision = '7321151c25a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('name', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'name')
    # ### end Alembic commands ###
