"""attendance table

Revision ID: 298a7e9b4646
Revises: 0184c586c2c8
Create Date: 2020-05-14 16:00:50.133360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '298a7e9b4646'
down_revision = '0184c586c2c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('temperature', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('score', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('hemacias', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('hematocritos', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('hemoglobinas', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('vcm', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('hcm', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('chcm', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('rdw', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('eritoblastos', sa.Integer(), nullable=True),
    sa.Column('leucocitos', sa.Integer(), nullable=True),
    sa.Column('mielocitos', sa.Integer(), nullable=True),
    sa.Column('metamielocitos', sa.Integer(), nullable=True),
    sa.Column('bastonetes', sa.Integer(), nullable=True),
    sa.Column('segmentados', sa.Integer(), nullable=True),
    sa.Column('neutrofilos_totais', sa.Integer(), nullable=True),
    sa.Column('eosinofilos', sa.Integer(), nullable=True),
    sa.Column('basofilos', sa.Integer(), nullable=True),
    sa.Column('linfocitos', sa.Integer(), nullable=True),
    sa.Column('monocitos', sa.Integer(), nullable=True),
    sa.Column('plasmocitos', sa.Integer(), nullable=True),
    sa.Column('pcr', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('plaquetas', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.Column('vmp', sa.Float(precision=10, asdecimal=2), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_timestamp'), 'attendance', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_timestamp'), table_name='attendance')
    op.drop_table('attendance')
    # ### end Alembic commands ###
