"""users update

Revision ID: 7f6e0b6cc38a
Revises: fed1813c0e09
Create Date: 2020-04-02 20:44:42.029077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f6e0b6cc38a'
down_revision = 'fed1813c0e09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('available_care_places', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('available_uti_places', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'available_uti_places')
    op.drop_column('user', 'available_care_places')
    # ### end Alembic commands ###
