"""users update

Revision ID: fed1813c0e09
Revises: 22091a5ca65a
Create Date: 2020-04-02 20:44:02.503896

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fed1813c0e09'
down_revision = '22091a5ca65a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('care_places', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('uti_places', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uti_places')
    op.drop_column('user', 'care_places')
    # ### end Alembic commands ###
